### DISCUSSION TITLE
Transition time to brightness?

### DISCUSSION THREAD

**Discussion by YanisKyr** [IATkachenko/HA-SleepAsAndroid#50] [Q&A] [answered]
Is it possible to use transition time to the set brightness? Instead of the bulb's default.

Thanks in advance.

**Comment by IATkachenko** [comment]
@YanisKyr, hello.

This integration is not about light, it is just allow integrate SleepAsAndroid Android application to Home Assistant as states and events.
Or I'm missing some thing in your question...

**Comment by YanisKyr** [comment]
Hi Igor, thanks for the reply. Love the integration and the blueprint by the way!

I'm using your blueprint to turn lights on/off based on SleepAsAndroid states, and I was trying to take advantage of the transition attribute [mentioned here](https://www.home-assistant.io/integrations/light/) to make the lights turn on/off gradually.

**_Example extract from the automation I'm referring to:_**
```
use_blueprint:
  path: IATkachenko/full.yaml
  input:
    device: eb7576862265a75cc89170f46bb0fe8c
    person: person.yaniskyr
    sleep_tracking_started:
      - type: turn_off
        device_id: e8249bdfa1d03d6a99fa9fbbbed26dad
        entity_id: light.2
        domain: light
    alarm_snooze_clicked:
      - type: turn_on
        device_id: e18e0523e9a444788d3ebfbbbd40ec12
        entity_id: light.3
        domain: light
        brightness_pct: 4
```

**_Example extract from another implementation with transition:_**
```
  action:
  - data:
      brightness_pct: 100
      transition: 18000
```

**Comment by IATkachenko** [comment, marked as answer]
@YanisKyr, you may use same settings in the integration blueprint.

My "live" configuration for `sleep_tracking_started` event for blueprint:
```yaml
service: light.turn_off
data:
  transition: 60
target:
  area_id:
    - b6b333fa2c114cb69f2d831fb4dd0263
    - 7259d193925047be89f17abd57c141cb
    - 755d515a3d1d421ab9d128394dd16496
    - 298a2461d54243ce9ea8e0f31b2f9491
```
Just use in action "run service" for event, then select service: `light.turn_off` or `light.turn_on` and enable checkbox
![изображение](https://user-images.githubusercontent.com/17473830/216827470-de04a8c7-005b-48f3-abce-5c18968cb6a1.png)

Also you may switch from visual to yaml mode while editing action (via three dots in action) and add any property that is not configurable via UI, but allowed by service configuration (but it looks like UI allow set any allowed property for service).
