### DISCUSSION TITLE
Label

### DISCUSSION THREAD

**Discussion by wiksito** [IATkachenko/HA-SleepAsAndroid#82] [Q&A]
Hi, thanks for making this integration. I'm absolutely new to this. How do I use label to only trigger the integration on specific alarm? For example: "work week" is the name/label of the alarm in SAA. Below is my yaml, where do i put label: "work week"? Thanks!

```yaml
alias: Sleep as Android
description: ""
use_blueprint:
  path: IATkachenko/full.yaml
  input:
    device: sensor.sleepasandroid_z
    person: person.z
    alarm_alert_start:
      - action: light.turn_on
        metadata: {}
        data: {}
        target:
          device_id: light.bulb02
```
