### ISSUE TITLE
Integration doesn't create device or anything...

### ISSUE THREAD

**Issue by franzbischoff** [IATkachenko/HA-SleepAsAndroid#17]
### Integration

**Integration version:** I tried the last one and the main branch from github

Last HACS version, last HA-OS version

### Application settings

**topic:** 
```
mqtt:
  broker: core-mosquitto
  port: 1883
  discovery: true

sleep_as_android:
  name: SleepAsAndroid
  topic_template: SleepAsAndroid/fbsleep
```
[x] I can see MQTT messages from application at MQTT-server

## How it works now?

I can use the MQTT integration to send (and receive in MyMQTT on android), and I can subscribe manually to the above topic and send it from the SleepAsAndroid, but the HACS integration doesn't create any device or logs anything on log (I've set the logger to debug).
