### ISSUE TITLE
Add an entity for the next scheduled alarm

### ISSUE THREAD

**Issue by arturbalabanov** [IATkachenko/HA-SleepAsAndroid#68]
Heya, thank you a lot for this integration, it's super useful!

One thing that would be nice to be included is an entity showing the next scheduled alarm which can be added to any dashboard. I just implemented this as a template sensor and works great, here's the YAML code:

```yaml
template:
  - trigger:
      - platform: mqtt
        topic: SleepAsAndroid/arti_s_pixel  # NOTE: this value will be different for other users, maybe we can automate it somehow
    action:
      variables:
        alarm_name: >
          {% if 'value2' in trigger.payload_json %}
            {{ trigger.payload_json.value2 }}
          {% else %}
            {{ none }}
          {% endif %}
        trigger_datetime: >
          {% if 'value1' in trigger.payload_json %}
            {{ (trigger.payload_json.value1 | int / 1000) | timestamp_local }}
          {% else %}
            {{ none }}
          {% endif %}
    sensor:
      - name: "SleepAsAndroid Alarm"
        unique_id: "sleep_as_android_alarm"
        device_class: timestamp
        icon: >
          {% if alarm_name is none %}
            mdi:alarm-off
          {% else %}
            mdi:alarm
          {% endif %}
        state: "{{ trigger_datetime | default('No scheduled alarm') }}"
        attributes:
          alarm_name: "{{ alarm_name }}"
          trigger_datetime: "{{ trigger_datetime }}"
```

Here's an example of a dashboard tile with it:

![Screenshot 2024-07-03 at 21 12 21](https://github.com/IATkachenko/HA-SleepAsAndroid/assets/3062003/77593aa2-dc6d-422f-9258-e5f9170c703a)

I've testing this with HAOS 2024.6.4. I'm new to home assistant, so I'm not sure what would be the best way to implement this into the integration but even if it's not a core feature, adding this snippet in the README would help other users who want something similar.
